// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9-Q9QhAEfZcE6ggZIq_YkLt8Q0luNaY',
    appId: '1:1064889172258:web:644b6aa8003657138c657b',
    messagingSenderId: '1064889172258',
    projectId: 'parafareapplication',
    authDomain: 'parafareapplication.firebaseapp.com',
    storageBucket: 'parafareapplication.firebasestorage.app',
    measurementId: 'G-74JBF84QJ3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzK9d3ZYRu8FlP09xidAgDCvxxK-QS4h8',
    appId: '1:1064889172258:ios:54f5948f6e19001b8c657b',
    messagingSenderId: '1064889172258',
    projectId: 'parafareapplication',
    storageBucket: 'parafareapplication.firebasestorage.app',
    iosBundleId: 'com.example.parafareApplication',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzK9d3ZYRu8FlP09xidAgDCvxxK-QS4h8',
    appId: '1:1064889172258:ios:54f5948f6e19001b8c657b',
    messagingSenderId: '1064889172258',
    projectId: 'parafareapplication',
    storageBucket: 'parafareapplication.firebasestorage.app',
    iosBundleId: 'com.example.parafareApplication',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyWSwiIQmxWRTJxfaauDeVB4fXL2LpG5M',
    appId: '1:1064889172258:android:22d77b8dcc7408ef8c657b',
    messagingSenderId: '1064889172258',
    projectId: 'parafareapplication',
    storageBucket: 'parafareapplication.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9-Q9QhAEfZcE6ggZIq_YkLt8Q0luNaY',
    appId: '1:1064889172258:web:638ae437323660618c657b',
    messagingSenderId: '1064889172258',
    projectId: 'parafareapplication',
    authDomain: 'parafareapplication.firebaseapp.com',
    storageBucket: 'parafareapplication.firebasestorage.app',
    measurementId: 'G-EYN6JNF9VV',
  );

}